apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090

  - name: Loki 
    type: loki 
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://loki:3100