{
 "title": "Flux2",
 "description": "Basic monitoring of FluxCD resources.",
 "tags": [
  "flux",
  "flux2",
  "gitops",
  "toolkit",
  "weave",
  "fluxcd"
 ],
 "time": { "from": "2025-03-08T14:23:55.252Z", "to": "2025-03-08T15:23:55.256Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_reconcile_condition, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_reconcile_condition{exported_namespace=~\"$namespace\",type=\"Ready\",status=\"True\",kind=~\"GitRepository|HelmRepository|OCIRepository\"})"
    }
   ]
  },
  {
   "title": "Failing sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gotk_reconcile_condition{exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|OCIRepository\"})"
    }
   ]
  },
  {
   "title": "Avg. source reconciliation",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|OCIRepository\"}[5m])) by (kind)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|OCIRepository\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_reconcile_condition{status=\"True\", kind=\"Kustomization\"})"
    }
   ]
  },
  {
   "title": "Failing application",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Sum(gotk_reconcile_condition{kind=~\"Kustomization\",status=\"False\"})"
    },
    {}
   ]
  },
  {
   "title": "Avg. app reconciliation",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source acquisition readiness ",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_join(gotk_reconcile_condition{exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|OCIRepository\"}, \"join_key\", \",\", \"kind\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(gotk_suspend_status{exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|OCIRepository\"} - 2, \"join_key\", \",\", \"kind\", \"exported_namespace\", \"name\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application reconciliation readiness ",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "label_join(gotk_reconcile_condition{exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"}, \"join_key\", \",\", \"kind\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(gotk_suspend_status{exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"} - 2, \"join_key\", \",\", \"kind\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "Timing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Source reconciliation duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind, exported_namespace, name)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind, exported_namespace, name)",
       "legendFormat": "{{kind}}: {{exported_namespace}}/{{name}}"
      }
     ]
    },
    {
     "title": "Application reconciliation duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name, exported_namespace)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name, exported_namespace)",
       "legendFormat": "{{kind}}: {{exported_namespace}}/{{name}}"
      }
     ]
    }
   ]
  }
 ]
}