apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"observability-loki-grafana-node-port","namespace":"observability"},"spec":{"ports":[{"nodePort":30000,"port":80,"targetPort":3000}],"selector":{"app.kubernetes.io/name":"grafana"},"type":"NodePort"}}
  creationTimestamp: "2025-03-10T01:48:34Z"
  name: observability-loki-grafana-node-port
  namespace: observability
  resourceVersion: "1612576"
  uid: 7adcda2a-7ca5-452b-ac17-f1a69c904f52
spec:
  clusterIP: 10.43.162.126
  clusterIPs:
  - 10.43.162.126
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
