proxmox_host         = "127.0.0.1:8006"
proxmox_node         = "pve"
proxmox_api_user     = "root@pam"
proxmox_api_password = "admin"
iso_file             = "~/Downloads/debian-12.9.0-amd64-netinst.iso"