version: '3.7'
services:
  loki:
    image: docker.io/grafana/loki:latest
    network_mode: "host"
    ports:
      - 3100:3100
    volumes:
      - ./configs/promtail-host-logs.yml:/etc/loki/loki-config.yaml