{{- if .Values.configData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-cm
data:
    {{ .Values.configData.configName }}: |
    {{ .Values.configData.config |toYaml | nindent 6}}
{{- end }}
