apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }} 
  labels:
    name: {{ .Values.name }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.name }} 
  template:
    metadata:
      labels:
        name: {{ .Values.name }} 
    spec:
      containers:
        - name: {{ .Values.name }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.imagePullSecrets }}    
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
              {{ .  }}            
            {{- end }}
          {{- end }}
          ports:
          {{- range .Values.ports }}
            - name: http
              containerPort: {{ . }}
              protocol: TCP
          {{- end }}
          env:
            {{- range $key, $value :=  .Values.env }}
            - name: {{$key }}
              value: {{ $value }}
            {{- end }}
