apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }} 
  labels:
    name: {{ .Values.name }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.name }} 
  template:
    metadata:
      labels:
        name: {{ .Values.name }} 
    spec:
      containers:
        - name: {{ .Values.name }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          {{- if .Values.imagePullSecrets }}    
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
              {{ .  }}            
            {{- end }}
          {{- end }}
          ports:
          {{- range .Values.ports }}
            - name: http
              containerPort: {{ . }}
              protocol: TCP
          {{- end }}

          {{- if or .Values.env .Values.secretEnv }}
          env:
            # Chart-based environment variables
            {{- range $key, $value :=  .Values.env }}
            - name: {{$key }}
              value: {{ $value }}
            {{- end }}
            # Secret-based environment variables
            {{- range $key, $secret := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.name }}
                  key: {{ $secret.key }}
            {{- end }}
            {{- end }}
            # end of env 

 
          {{- if .Values.volumes }}    
          volumeMounts:
            {{- range .Values.volumes }}
            - mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              name: {{ .name }}-volume
            {{- end }}
          {{- end }}

      volumes:
        - name: {{ .Values.name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-pvc