apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}-svc
spec:
  selector:
    name: {{ .Values.name }}
  ports:
    {{- range .Values.service }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}