# One pv and 
{{- if .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
spec:
  resources: 
    requests:
      storage: {{ .Values.storage.capacity }}
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
{{- end }}