# One pv and 
{{- if .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
spec:
  capacity: 
    storage: {{ .Values.storage.capacity }}
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: {{ .Values.name }}-pvc
#   hostPath:
#     path: "/var/lib/rancher/k3s/storage/{{ .Values.name }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
spec:
  resources: 
    requests:
      storage: {{ .Values.storage.capacity }}
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
{{- end }}