version: '3.7'
services:
  prometheus:
    networks:
      - observability
    image: docker.io/prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ~./grafana/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    networks:
      - observability
    ports:
      - 9100:9100
  
  grafana:
    networks:
      - observability
    image: docker.io/grafana/grafana
    ports:
      - 3000:3000
    volumes:
    - ./grafana/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
    - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    - ./grafana/dashboards:/var/lib/grafana/dashboards

networks:
  observability:
    external: true