version: '3.7'
services:
  loki:
    image: docker.io/grafana/loki:latest
    networks:
      - observability
    ports:
      - 3100:3100
    volumes:
      - ./loki-promtail-config/loki-config.yml:/etc/loki/loki-config.yaml

  promtail:
    command: 
    - --config.file=/etc/promtail/config.yml
    - --server.enable-runtime-reload
    networks:
      - observability
    image: docker.io/grafana/promtail:latest
    volumes:
      -  ~/.local/share/containers/storage/overlay-containers:/containers/storage/overlay-containers
      - /var/log:/var/log:ro
      - ./loki-promtail-config/promtail-config.yml:/etc/promtail/config.yml
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
networks:
  observability:
    external: true