# Deployments
name: appname
replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

env: 
  ENV: STAGING
  user: admin

secretEnv: {} 
  # DB_USER:
  #   name: db-secret
  #   key: db-username
  # DB_PASSWORD:
  #   name: db-secret
  #   key: db-password

initContainer:
  enable: false
  img: busybox
  cmd: "bin/bash chmod 755 -R /config"


resources: {}
  # requests:
    # cpu: "128m"
    # memory: 128Mi
  # limits:
    # cpu: "512m"
    # memory: 512Mi
# 
# storage 
volumes: 
  - mountPath: "/mnt/shared-data"
    subPath: "k3s"  # This points to /var/lib/rancher/k3s/storage/subPath

storage: 
  capacity: "1Gi"  # max size that can be allocated to pv/pvc
  hostPath: /var/lib/rancher/k3s/storage

# Networking
ports: 
  - 80

# Attaching a config as a volume
configData: {}
  # path: /tmp/config.yaml
  # configKey: config
  # config:
    # foo: bar
    # test:
      # foo: bar
# 
service: 
  - protocol: TCP
    port: 80
    targetPort: 80

ingress: 
  - path: /my-path
    pathType: Prefix
    port: 80
    service: appname-service