# Deployments
name: appname
replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

env: 
  ENV: STAGING
  user: admin

resources:
  requests:
    cpu: "128m"
    memory: 128Mi
  limits:
    cpu: "512m"
    memory: 512Mi

# storage 
volumes: 
  - mountPath: "/mnt/shared-data"
    subPath: "k3s"  # This points to /var/lib/rancher/k3s/storage/{{ .Values.name }}/data1
    name: appname # need to match .values.name, cant reference .Values inside forloop, reverences pvc

storage: 
  capacity: "1Gi"  # max size that can be allocated to pv/pvc

# Networking
ports: 
  - 80

service: 
  - protocol: TCP
    port: 80
    targetPort: 80

ingress: 
  - path: /my-path
    pathType: Prefix
    port: 80
    service: appname-service