
# Deployments
name: appname
replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

env: 
  ENV: STAGING
  user: admin


volumes: []

ports: 
  - 80

# Networking
service: 
  - protocol: TCP
    port: 80
    targetPort: 80

ingress: 
  - path: /my-path
    pathType: Prefix
    port: 80
    service: appname-service
