apiVersion: v1
kind: Service
metadata:
  name: observability-loki-grafana-node-port
  namespace: observability
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000  # Expose Grafana on a fixed port (32000)
---