apiVersion: v1
kind: PersistentVolume
metadata:
  name: observability-host
  labels:
    local: observability-host
spec:
  capacity:
    storage: 50Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/shef/media/hd-10/lab/observability
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - "true" 